import { notFound } from "next/navigation";

import { StatusBadge } from "@/components/premium/primitives";
import { ListingRestrictionControls, NsfasAccreditationControls } from "@/features/admin/components/admin-actions";
import { AdminHeader, DetailList } from "@/features/admin/components/admin-ui";
import { getAdminListing } from "@/features/admin/data";
import { formatPrice } from "@/lib/utils";

export default async function AdminListingDetailPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const data = await getAdminListing(id); if (!data) notFound(); const active = data.restrictions.find((item) => !item.restored_at); const nsfasApproved = Boolean(data.accreditation?.nsfas_approved); return <><AdminHeader title={data.listing.title} description={data.listing.address} /><div className="mb-4 flex flex-wrap gap-2"><StatusBadge>{data.listing.status}</StatusBadge>{active ? <StatusBadge tone="error">Hidden from public discovery</StatusBadge> : <StatusBadge tone="success">Public visibility allowed</StatusBadge>}{nsfasApproved ? <StatusBadge tone="forest">NSFAS Approved</StatusBadge> : <StatusBadge tone="neutral">Not NSFAS approved</StatusBadge>}</div><DetailList items={[{ label: "Listing ID", value: data.listing.id }, { label: "Landlord", value: data.listing.landlord?.full_name || data.listing.landlord?.email || data.listing.landlord_id }, { label: "Price", value: formatPrice(data.listing.price) }, { label: "Created", value: new Date(data.listing.created_at).toLocaleString("en-ZA") }, { label: "NSFAS verified", value: data.accreditation?.verified_at ? new Date(data.accreditation.verified_at).toLocaleString("en-ZA") : "Not verified" }]} /><div className="mt-4 grid gap-4 lg:grid-cols-2"><ListingRestrictionControls listingId={id} restricted={Boolean(active)} /><NsfasAccreditationControls listingId={id} approved={nsfasApproved} /></div></>; }
